Pokdle/Controllers/MainController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Pokdle.Infrastructure;
using Pokdle.Models.ComponentModels;
using Pokdle.Models.PageModels;
using Pokdle.Repositories;
using PokeApiNet;
using Pokdle.Models;
using Microsoft.Extensions.Caching.Memory;
using System.Linq.Expressions;

namespace Pokdle.Controllers
{
    public class MainController : Controller
    {
        private readonly PokemonRepository _pokemonRepository;
        private PokemonInfo _pokemonOfTheDay;
        private static List<Pokemon> _pokemonList;
        private readonly IConfiguration _configuration;
        public MainController(IConfiguration configuration, PokemonRepository pokemonRepo, List<Pokemon> listOfPokemon)
        {
            _pokemonRepository = pokemonRepo;
            _configuration = configuration;
            _pokemonOfTheDay = GetCurrentPokemon();
            _pokemonList = _pokemonList ?? listOfPokemon;
        }

        public async Task<IActionResult> Index(bool isRandom = false, int seed = 0)
        {
            MainPageModel model = new MainPageModel();
           // _pokeNode = pokemonNode ?? _pokeNode;
            string cachedRandomKey = seed > 0 ? "Random" : "";
            List<PokemonInfo> pokemonGuessesInfoList = HttpContext.Session.GetComplexData<List<PokemonInfo>>($"{cachedRandomKey}PokemonInfoGuesses") ?? new List<PokemonInfo>();
            List<Guess> guesses = HttpContext.Session.GetComplexData<List<Guess>>($"{cachedRandomKey}Guesses") ?? new List<Guess>();
            seed = seed == 0 ? HttpContext.Session.GetInt32("RandomSeed") ?? seed : seed;
            _pokemonOfTheDay = seed > 0 ? GetCurrentPokemon(seed) : _pokemonOfTheDay;
            isRandom = !isRandom ? Convert.ToBoolean(HttpContext.Session.GetString("IsRandom") ?? "false") : isRandom;
            model.IsRandomMode = isRandom;
            model.IsSuccess = guesses.Any() ? guesses.Last().IsCorrect : false;
            model.RandomSeed = seed;
            model.BaseUrl = _configuration["BaseUrl"];
            model.PokemonName = _pokemonOfTheDay.Pokemon.Name.ToLowerInvariant();
            model.PokemonGuesses = new PokemonGuessComponentModel(pokemonGuessesInfoList, guesses);
            model.PokemonResults = new PokemonSearchComponentModel(_pokemonList);
            model.GenerationsList = _configuration.GetSection("GenerationsList").Get<List<string>>();
            return View(model);
        }

        public IActionResult SearchPokemon(string searchTerm, int seed, string generation)
        {
            string mode = seed > 0 ? "Random" : "";
            List<PokemonInfo> pokemonGuessesInfoList = HttpContext.Session.GetComplexData<List<PokemonInfo>>($"{mode}PokemonInfoGuesses") ?? new List<PokemonInfo>();
            var searchResults = int.TryParse(searchTerm, out int id) ? 
                Search.SearchById(id, pokemonGuessesInfoList.Select(p => p.Pokemon.Id).ToList(), _pokemonList, generation)
                :Search.SearchByName(searchTerm, pokemonGuessesInfoList.Select(p => p.Pokemon.Id).ToList(), _pokemonList, generation);         
            return ViewComponent("PokemonDropdown", new PokemonSearchComponentModel(searchResults));
        }
        public async Task<IActionResult> TryGuess(string id, int seed = 0)
        {
            PokemonInfo guessInfo = new PokemonInfo();
            _pokemonOfTheDay = seed > 0 ? await DailyPokemon.GetDailyPokemon(_pokemonRepository, int.Parse(_configuration["PokemonTotal"]), seed) : _pokemonOfTheDay;
            string cachedRandomKey = seed > 0 ? "Random" : "";
            guessInfo.Pokemon = await _pokemonRepository.GetPokemon(id);
            guessInfo.Species = await _pokemonRepository.GetPokemonSpecies(id);
            guessInfo.EvolutionChain = await _pokemonRepository.GetEvolutionChain(guessInfo.Species.EvolutionChain.Url);
            guessInfo.EvolutionStage = await _pokemonRepository.GetEvolutionStage(guessInfo.Species);
            var guess = new GuessChecker();
            var guessResults = guess.CheckGuess(guessInfo, _pokemonOfTheDay);
            List<PokemonInfo> currentInfo = HttpContext.Session.GetComplexData<List<PokemonInfo>>($"{cachedRandomKey}PokemonInfoGuesses") ?? new List<PokemonInfo>();
            List<Guess> currentGuesses = HttpContext.Session.GetComplexData<List<Guess>>($"{cachedRandomKey}Guesses") ?? new List<Guess>();
            currentInfo.Add(guessInfo);
            currentGuesses.Add(guessResults);
            HttpContext.Session.SetComplexData($"{cachedRandomKey}PokemonInfoGuesses", currentInfo);
            HttpContext.Session.SetComplexData($"{cachedRandomKey}Guesses", currentGuesses);
            return ViewComponent("PokemonGuess", new PokemonGuessComponentModel(currentInfo, currentGuesses));
        }
        public IActionResult RandomMode()
        {
            Random rnd = new Random();
            int seed = rnd.Next();
            HttpContext.Session.SetInt32("RandomSeed", seed);
            HttpContext.Session.SetString("IsRandom", "true");
            return RedirectToAction("Index", new { isRandom = true, seed = seed });
        }
        public IActionResult DailyMode()
        {
            HttpContext.Session.Remove("RandomPokemonInfoGuesses");
            HttpContext.Session.Remove("RandomGuesses");
            HttpContext.Session.SetInt32("RandomSeed", 0);
            HttpContext.Session.SetString("IsRandom", "false");
            return RedirectToAction("Index");
        }
        private PokemonInfo GetCurrentPokemon(int seed = 0)
        {
            PokemonInfo newPokemon = new PokemonInfo();

            while (newPokemon.Pokemon == null)
            {
                try
                {
                    newPokemon = DailyPokemon.GetDailyPokemon(_pokemonRepository, int.Parse(_configuration["PokemonTotal"]) + 1, seed).GetAwaiter().GetResult();
                }
                catch
                {

                }
            }
            return newPokemon;
        }
    }
}

Pokdle/ViewComponents/PokemonDropdownViewComponent.cs
using Pokdle.Models.ComponentModels;
using Microsoft.AspNetCore.Mvc;

namespace Pokdle.ViewComponents
{
    public class PokemonDropdownViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PokemonSearchComponentModel model)
        {
            return View(model);
        }
    }
}

Pokdle/ViewComponents/PokemonGuessViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Pokdle.Models.ComponentModels;
namespace Pokdle.ViewComponents
{
    public class PokemonGuessViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(PokemonGuessComponentModel model)
        {
            return View(model);
        }
    }
}

Pokdle/Views/Main/Index.cshtml
@using PokeAPI
@model Pokdle.Models.PageModels.MainPageModel
    <div class="text-center card mainCard">
        <h1 class="display-4 pokeFont mainTitle">Pokdle</h1>
        <br />
        <h6 class="pokeFont pokeText">Another Pokemon Wordle Clone</h6>
        @if(Model.IsRandomMode)
        {
        <h6 class="pokeFont pokeText">Random Mode</h6>
        }
    <br />
    @if (!Model.IsSuccess)
    {
    <div id="cluesDiv">
            <h3 class="textcolor">Clues</h3>
            @if(Model.PokemonGuesses.Guesses.Count < 3)
            {
                <h6 class="textcolor" id="triesLeft">@(3 - Model.PokemonGuesses.Guesses.Count) tries left to unlock this clue</h6>
            }           
        <button class="btn pokeFont pokeText @(Model.PokemonGuesses.Guesses.Count >= 3 ? "btn-primary" : "")" id="cryBtn" @(Model.PokemonGuesses.Guesses.Count >= 3 ? "" : "disabled") onclick="playCry('@Model.PokemonName')">
            <img class="clueSize" src="~/resources/soundwave.png"/>
            <br/>
            Cry
        </button>
    </div>
    
        <div class="row d-flex justify-content-center" id="pokeSearchDiv">
         <div class="form-group">
            <label for="searchPokemon">Try it out!</label>
                <div class="dropdown">
                    <div class="textcolor">Generation</div>
                    <button class="btn dropdown-toggle" type="button" id="GenSelectDropdownButton" aria-expanded="false">
                        All
                    </button>
                    <ul class="dropdown-menu dropdown-menu-light" id="GenSelectDropdown" aria-labelledby="GenSelectDropdownButton">
                        @foreach(string gen in Model.GenerationsList)
                        {
                            <li><a class="dropdown-item" style="text-align:center" id="generation-@gen" href="#" onclick="SetGeneration('@gen')">@gen</a></li>
                        }
                    </ul>
                </div>
            
            <div class="dropdown col-xs-3">
                    <input class="btn btn-secondary-dropdown form-control" type="text" onkeyup="pokeSearch()" id="searchPokemon" aria-expanded="false" placeholder="Guess a Pokemon" value="" />
                <ul class="dropdown-menu dropdown-menu-light pokemonDropdown" id="SearchPokemonDropdownList" aria-labelledby="searchPokemon">
                    @await Component.InvokeAsync("PokemonDropdown", Model.PokemonResults)
                </ul>       
            <input type="hidden" name="selectedPokemon" id="selectedPokemonDropdown" value="0" />
           </div>
        </div>
        </div>
  <div id="submitDiv">
      <button type="submit" class="btn btn-primary" id="submitGuess" onclick="SubmitGuess()">Submit</button>
  </div>
  
   }
   <br/>
   <form action="Main/@(!Model.IsRandomMode ? "RandomMode": "DailyMode")" method="Get">
       <button type="submit" class="btn btn-warning" id="changeMode">@(!Model.IsRandomMode ? "Go to Random Mode" : "Pokemon of the Day")</button>
   </form>
<br />
</div>
<div id="guessDiv">
    <table class="table tableGuesses">
        <thead class="columnHeader">
            <tr class="pokeFont pokeText tableHead">    
                <th scope="col">
                    <div class="tooltip1">
                        Pokemon
                        <span class="tooltiptext1 tooltip-top1">The Pokemon's official artwork</span>
                    </div>
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Type
                        <span class="tooltiptext1 tooltip-top1">The Pokemon's typing.</span>
                    </div>
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Abilities
                        <span class="tooltiptext1 tooltip-top1">The Pokemon's abilities. Includes Hidden Abilities </span>
                    </div>
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Top Two Base Stats
                        <span class="tooltiptext1 tooltip-top1">The Pokemon's two highest base stats.</span>
                    </div>
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Lowest Two Base Stats
                        <span class="tooltiptext1 tooltip-top1">The Pokemon's two lowest base stats.</span>
                    </div>    
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Evolution Stage
                        <span class="tooltiptext1 tooltip-top1">The stage of evolution the Pokemon is in.</span>
                    </div>            
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Evolution Line Total
                        <span class="tooltiptext1 tooltip-top1">The total number of Pokemon in the Pokemon's evolutionary line, including the first stage and branching evolutions.</span>
                    </div>
                </th>
                <th scope="col">
                    <div class="tooltip1">
                        Generation
                        <span class="tooltiptext1 tooltip-top1">The Pokemon's debut generation.</span>
                    </div>
                </th>
           </tr>
        </thead>
        <tbody id="guessTbody" class="pokeFont pokeText">
            @await Component.InvokeAsync("PokemonGuess", Model.PokemonGuesses)
        </tbody>
    </table>
</div>
    <div class="row">
        <div class="col-sm-2">
            <div class="card">
                <img class="card-img-top clueSize" src="~/resources/greenblock.png" alt="Card image cap">
                <div class="card-body pokeFont pokeText">
                    Correct
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="card">
                <img class="card-img-top clueSize" src="~/resources/yellowblock.png" alt="Card image cap">
                <div class="card-body pokeFont pokeText">
                    Partially Correct
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="card">
                <img class="card-img-top clueSize" src="~/resources/redblock.png" alt="Card image cap">
                <div class="card-body pokeFont pokeText">
                    Incorrect
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="card">
                <img class="card-img-top clueSize" src="~/resources/white-up-arrow-png-2.png" alt="Card image cap">
                <div class="card-body pokeFont pokeText">
                    Answer is greater than
                </div>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="card">
                <img class="card-img-top clueSize" src="~/resources/white-down-arrow-png-2.png" alt="Card image cap">
                <div class="card-body pokeFont pokeText">
                    Answer is less than
                </div>
            </div>
        </div>
    </div>
    @if (Model.IsSuccess)
    {
        <br/>
     <div class="row">
        <div class="col-sm-5">
            <div class="card">
                <div style="color:black">
                    You guessed the @(@Model.IsRandomMode ? "Random Pokemon" : "Pokemon of the day") in @Model.PokemonGuesses.Guesses.Count @(Model.PokemonGuesses.Guesses.Count == 1 ? "try" : "tries")!
                </div>
            <br/>
                <button id="copyButton" class="btn btn-primary">Copy</button>
                <input type="hidden" id="guessCount" value="@Model.PokemonGuesses.Guesses.Count" />
                @if (Model.IsRandomMode)
                {
                    <br/>
                    <form action="Main/RandomMode" method="Get">
                        <button type="submit" class="btn btn-warning" id="changeMode">Try Another Random Pokemon</button>
                    </form>
                }                
            </div>
        </div>
    </div>
    }
    
<input type="hidden" id="randomSeed" value="@Model.RandomSeed" />
<input type="hidden" id="baseUrl" value="@Model.BaseUrl" />